name: normalize

on:
  workflow_dispatch: null
  schedule:
    - cron: 0 0 * * 0

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  normalize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Normalize
        run: |
          node normalize.mjs
      - uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Normalized
          branch: normalized
          branch-suffix: timestamp
          title: Normalized
